# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Web3-native software distribution."
  homepage "https://valist.io"
  version "0.6.3"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/valist-io/valist/releases/download/v0.6.3/valist_0.6.3_darwin_arm64.tar.gz"
      sha256 "79cfb4e9cab78c0358f483db9afa1e5f4021af02937abb4d7c0d2f6cfc536703"

      def install
        bin.install "valist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/valist-io/valist/releases/download/v0.6.3/valist_0.6.3_darwin_amd64.tar.gz"
      sha256 "48c11bf9da6dba404bba7cab634fc9f607598d9b9e439ce8560c3b9d5131566c"

      def install
        bin.install "valist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/valist-io/valist/releases/download/v0.6.3/valist_0.6.3_linux_amd64.tar.gz"
      sha256 "b50aa94f42ed1c49ed6cd5764c9ca9b3e3d0fde5a605f8ed74ad8ca8bcb05f3c"

      def install
        bin.install "valist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valist-io/valist/releases/download/v0.6.3/valist_0.6.3_linux_arm64.tar.gz"
      sha256 "ab3275e6ce83c5b707a1eba3e30fd718722af321d1cf3a9254c28b7ff73552bb"

      def install
        bin.install "valist"
      end
    end
  end
end
