# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Web3-native software distribution."
  homepage "https://valist.io"
  version "0.6.2"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valist-io/valist/releases/download/v0.6.2/valist_0.6.2_darwin_amd64.tar.gz"
      sha256 "335d5351ef5ea44b58a8d53db17636dbbd67a70f22b1187ea75d050091100b97"

      def install
        bin.install "valist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valist-io/valist/releases/download/v0.6.2/valist_0.6.2_darwin_arm64.tar.gz"
      sha256 "e3f9d88e6e298e27942708bc85144ab79202e5cbfbdda8d2a6eee28a85a5ac61"

      def install
        bin.install "valist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valist-io/valist/releases/download/v0.6.2/valist_0.6.2_linux_arm64.tar.gz"
      sha256 "7c76f43e65512cea7a5b2968ed60510e8a1a3808ca9168849690240b331e8bb8"

      def install
        bin.install "valist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/valist-io/valist/releases/download/v0.6.2/valist_0.6.2_linux_amd64.tar.gz"
      sha256 "5bd64a321a8cb589e068899b6494cb28aa408ada21afc0780a29862ae811eced"

      def install
        bin.install "valist"
      end
    end
  end
end
