# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Web3-native software distribution."
  homepage "https://valist.io"
  version "0.6.3"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valist-io/valist/releases/download/v0.6.3/valist_0.6.3_darwin_amd64.tar.gz"
      sha256 "abe4009688bc20aa2bcff902757f4af6d1dce0c9cb945a7f706b9d078c896da7"

      def install
        bin.install "valist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valist-io/valist/releases/download/v0.6.3/valist_0.6.3_darwin_arm64.tar.gz"
      sha256 "3e4d606535089cbc655f361dd4fd945319e3be06fba67b881f8c8b6c5ba3c794"

      def install
        bin.install "valist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valist-io/valist/releases/download/v0.6.3/valist_0.6.3_linux_arm64.tar.gz"
      sha256 "c7138d91f3ae17a72d3fda39be19be85de019c8b482ac112c63c5326c545c21f"

      def install
        bin.install "valist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/valist-io/valist/releases/download/v0.6.3/valist_0.6.3_linux_amd64.tar.gz"
      sha256 "94e32d10ccdb3d95528155adf169f72fb638154548daec84004dc2fff57a76fa"

      def install
        bin.install "valist"
      end
    end
  end
end
