# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valist < Formula
  desc "Universal package repositories, code signing, and access control."
  homepage "https://valist.io"
  version "0.6.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/valist-io/valist/releases/download/v0.6.0/valist_0.6.0_darwin_arm64.tar.gz"
      sha256 "aa975c566f9a16bc11ea54b1ab0effc1af0b9bfdf76664c4a799871e64763d23"

      def install
        bin.install "valist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/valist-io/valist/releases/download/v0.6.0/valist_0.6.0_darwin_amd64.tar.gz"
      sha256 "1a1fa3a2d4a6ccce88cfc625aa291f61cc1a6a772195985bf7c497be96150e69"

      def install
        bin.install "valist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valist-io/valist/releases/download/v0.6.0/valist_0.6.0_linux_arm64.tar.gz"
      sha256 "081016effd85a319fa760fa35b74244e581d70e69820505272e34587664cf8db"

      def install
        bin.install "valist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/valist-io/valist/releases/download/v0.6.0/valist_0.6.0_linux_amd64.tar.gz"
      sha256 "0cc7dfe1cd50bacc0ef4c0e287a04e70e499448dfce6fc24a8f7538cc1e436ba"

      def install
        bin.install "valist"
      end
    end
  end
end
